spring:
  application:
    name: agile-board

  datasource:
    url: jdbc:mysql://localhost:3306/agile_board?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin

server:
  port: 8080

logging:
  level:
    com.example.agileboard: DEBUG
    org.springframework.security: DEBUG
